name: leitorqrcode
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.11
  qr_code_scanner: ^1.0.0
  sqflite: ^2.0.2+1
  cupertino_icons: ^1.0.0
  path: ^1.8.0
  uuid: ^3.0.6
  http: ^0.13.4
  http_interceptor: ^1.0.2
  flutter_beep: ^1.0.0
  flutter_blue: 0.8.0
  rxdart: ^0.26.0
  input_with_keyboard_control: ^1.0.8
  flutter_easyloading: ^3.0.5
  animated_card: ^2.0.0
  bluetooth_connector: ^0.0.3
  f_logs: ^2.0.1
  share_plus: ^4.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: ArmazenamentoApp
      fonts:
        - asset: assets/fonts/ArmazenamentoApp.ttf
    - family: MWAppFont
      fonts:
        - asset: assets/fonts/MWAppFont.ttf
    - family: EcoFont
      fonts:
        - asset: assets/fonts/EcoFont.ttf