/// Flutter icons MWAppFont
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MWAppFont
///      fonts:
///       - asset: fonts/MWAppFont.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MWAppFont {
  MWAppFont._();

  static const _kFontFam = 'MWAppFont';
  static const String _kFontPkg = null;

  static const IconData adress =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData product_reload =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData items_reload =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_reload =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
